import traceback
from enum import StrEnum
from pathlib import PurePosixPath
from typing import Any, ClassVar, Self, get_args, get_origin, override

from pydantic import BaseModel, ConfigDict, SerializeAsAny


class Status(StrEnum):
    """Possible outcomes for one update task."""

    UPDATED = "updated"
    UP_TO_DATE = "up-to-date"
    SKIPPED = "skipped"
    FAILURE = "failure"


class Schedule(StrEnum):
    """Cadence selected for a scheduled update run."""

    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"


class RepositoryRef(BaseModel):
    """Remote repository identity selected for an update run."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    owner: str
    name: str
    branch: str | None = None

    @classmethod
    def parse(
        cls,
        spec: str,
        *,
        default_owner: str | None,
        default_branch: str | None = None,
    ) -> RepositoryRef:
        """Parse ``repo``, ``owner/repo`` or ``repo@branch``."""
        repo_spec, separator, inline_branch = spec.strip().partition("@")
        branch = inline_branch if separator else default_branch

        parts = repo_spec.split("/")
        if len(parts) == 2:
            owner, name = parts
        elif len(parts) == 1:
            if default_owner is None:
                msg = f"Repository spec {spec!r} requires a default owner."
                raise ValueError(msg)
            owner, name = default_owner, repo_spec
        else:
            msg = f"Invalid repository spec: {spec!r}"
            raise ValueError(msg)

        if not owner or not name:
            msg = f"Invalid repository spec: {spec!r}"
            raise ValueError(msg)

        return cls(owner=owner, name=name, branch=branch or None)

    @property
    def full_name(self) -> str:
        return f"{self.owner}/{self.name}"

    @property
    def display_name(self) -> str:
        if self.branch is None:
            return self.full_name
        return f"{self.full_name}@{self.branch}"


class UpdateItem(BaseModel):
    """A concrete task generated by preparing a repository for an updater."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    repository_ref: RepositoryRef

    @override
    def __str__(self) -> str:
        return self.repository_ref.display_name

    def log_prefix(self) -> str:
        return f"[{self}]"


class UpdateItemTypeMixin:
    """Mixin for classes that declare an update item type via generics."""

    item_type: ClassVar[type[UpdateItem]] = UpdateItem

    def __init_subclass__(cls, **kwargs: Any) -> None:
        super().__init_subclass__(**kwargs)
        if "item_type" not in cls.__dict__:
            cls.item_type = _infer_update_item_type(cls) or cls.item_type


class PathUpdateItem(UpdateItem):
    """Update item for tasks scoped to a repository path."""

    path: PurePosixPath = PurePosixPath(".")

    @override
    def __str__(self) -> str:
        if self.path == PurePosixPath("."):
            return self.repository_ref.display_name
        return f"{self.repository_ref.display_name} {self.path}"


class ScheduledUpdateItem(UpdateItem):
    """Update item for tasks generated from a scheduled source."""

    schedule: Schedule


class ScheduledPathUpdateItem(PathUpdateItem):
    """Update item for tasks scoped to both a repository path and schedule."""

    schedule: Schedule


class Diagnostics(BaseModel):
    """Human-readable message and optional extra debug details."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    message: str | None = None
    details: str | None = None

    @classmethod
    def from_exception(cls, error: BaseException, **kwargs: Any) -> Self:
        """Build an instance with the exception message and formatted traceback.

        Falls back to the exception type name when the exception has no message.
        """
        return cls(
            message=str(error) or type(error).__name__,
            details="".join(traceback.format_exception(error)).rstrip("\n"),
            **kwargs,
        )


class ScanFailure(Diagnostics):
    """Scanner failure captured for update result artifacts."""

    repository_ref: RepositoryRef


class UpdateOutput(BaseModel):
    """Typed data returned by updater implementation code."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class UpdateOutputTypeMixin:
    """Mixin for classes that declare an update output type via generics."""

    output_type: ClassVar[type[UpdateOutput]] = UpdateOutput

    def __init_subclass__(cls, **kwargs: Any) -> None:
        super().__init_subclass__(**kwargs)
        if "output_type" not in cls.__dict__:
            cls.output_type = _infer_update_output_type(cls) or cls.output_type


class UpdateOptions(BaseModel):
    """Typed CLI/runtime options for an updater."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class UpdateOutcome[OutputT: UpdateOutput = UpdateOutput](Diagnostics):
    """The outcome returned by updater implementation code."""

    result: Status
    pull_request_number: int | None = None
    output: SerializeAsAny[OutputT] | None = None


class UpdateResult[
    OutputT: UpdateOutput = UpdateOutput,
    ItemT: UpdateItem = UpdateItem,
](Diagnostics):
    """The structured result of running one update item."""

    result: Status
    item: SerializeAsAny[ItemT]
    pull_request_number: int | None = None
    output: SerializeAsAny[OutputT] | None = None

    @staticmethod
    def from_outcome[
        ResultOutputT: UpdateOutput,
        ResultItemT: UpdateItem,
    ](
        outcome: UpdateOutcome[ResultOutputT],
        *,
        item: ResultItemT,
    ) -> UpdateResult[ResultOutputT, ResultItemT]:
        return UpdateResult[ResultOutputT, ResultItemT](
            result=outcome.result,
            item=item,
            pull_request_number=outcome.pull_request_number,
            output=outcome.output,
            message=outcome.message,
            details=outcome.details,
        )


def _infer_update_item_type(cls: type[Any]) -> type[UpdateItem] | None:
    for base in getattr(cls, "__orig_bases__", ()):
        origin = get_origin(base)
        if not isinstance(origin, type) or not issubclass(origin, UpdateItemTypeMixin):
            continue
        item_type = get_args(base)[0]
        if not isinstance(item_type, type) or not issubclass(item_type, UpdateItem):
            msg = f"{cls.__name__} item type must be a subclass of UpdateItem."
            raise TypeError(msg)
        return item_type
    return None


def _infer_update_output_type(cls: type[Any]) -> type[UpdateOutput] | None:
    for base in getattr(cls, "__orig_bases__", ()):
        origin = get_origin(base)
        if not isinstance(origin, type) or not issubclass(
            origin, UpdateOutputTypeMixin
        ):
            continue
        output_type = get_args(base)[1]
        if not isinstance(output_type, type) or not issubclass(
            output_type, UpdateOutput
        ):
            msg = f"{cls.__name__} output type must be a subclass of UpdateOutput."
            raise TypeError(msg)
        return output_type
    return None
