"""Generate frontend contracts from their Pydantic models."""

import argparse
import json
from pathlib import Path

from pydantic import BaseModel

from quant_ranger._impl.aggregators._copier_dashboard import CopierDashboard
from quant_ranger._impl.aggregators._updater_report import UpdaterIndex, UpdaterReport

_ROOT = Path(__file__).resolve().parents[1]
_OUTPUT = _ROOT / "frontend/src/generated/frontend-contracts.ts"
_CONTRACTS = (
    (
        "copierDashboardSchema",
        CopierDashboard,
        "https://github.com/Quantco/quant-ranger/schemas/copier-dashboard.json",
    ),
    (
        "updaterReportSchema",
        UpdaterReport,
        "https://github.com/Quantco/quant-ranger/schemas/updater-report.json",
    ),
    (
        "updaterIndexSchema",
        UpdaterIndex,
        "https://github.com/Quantco/quant-ranger/schemas/updater-index.json",
    ),
)


def _model_schema(model: type[BaseModel], schema_id: str) -> dict[str, object]:
    schema = model.model_json_schema(mode="serialization")
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": schema_id,
        **schema,
    }


def _render() -> str:
    schemas = "\n\n".join(
        f"export const {name} = "
        f"{json.dumps(_model_schema(model, schema_id), indent=2)} as const"
        for name, model, schema_id in _CONTRACTS
    )
    return (
        "// Generated by scripts/generate_frontend_contracts.py.\n"
        "// Do not edit by hand.\n\n"
        f"{schemas}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the generated contracts are stale.",
    )
    options = parser.parse_args()
    generated = _render()
    if options.check:
        if not _OUTPUT.exists() or _OUTPUT.read_text(encoding="utf-8") != generated:
            print(
                f"{_OUTPUT.relative_to(_ROOT)} is stale; "
                "run `pixi run generate-frontend-contracts`."
            )
            return 1
        return 0

    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
